# ATTENTION
# This plugin uses some dangerous code to change a players name
# As this is not normal behaviour for the Minecraft/Bukkit server and installed plugins, unexpected results could occur
# We ask that you keep regular backups in the case of this happening
# The developer(s) of UUIDCompatibility take no responsibility for damage caused by this plugin
# YOU HAVE BEEN WARNED

# By changing this value to true, you show that you have read the above warning
enabled: false

showOriginalNameIn:
  # Show original name as display name
  displayName: false
  # Show original name in tab list
  tabList: false
  # Plugins which should be given UUID compatibility (tricked into thinking a players name is their original name)
  plugins:
    - GriefPrevention
# When a player joins and their username differs from their original name, should they be notified?
notifyPlayers: true