# ATTENTION
# This plugin uses some dangerous code to change a players name
# As this is not normal behaviour for the Minecraft/Bukkit server and installed plugins, unexpected results could occur
# We ask that you keep regular backups in the case of this happening
# The developer(s) of UUIDCompatibility take no responsibility for damage caused by this plugin
# YOU HAVE BEEN WARNED

# enabled - Enables the plugin, by changing this value to true, you show that you have read the above warning
# showOriginalNameIn - Locations in which players original names should be used
#   displayName - Show original name in display name
#   tabList - Show original name in tab list
#   plugins - A list of plugins which should be given UUID compatibility
# notifyPlayers - When a player joins and their username differs from their original name, should they be notified?

enabled: false

showOriginalNameIn:
  displayName: false
  tabList: false
  plugins:
    - GriefPrevention

notifyPlayers: true